apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch:

jobs:
  job-1:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Register artifacts 2
        id: register
        uses: cloudbees-io/register-build-artifacts@main
        with:
          artifact-metadata: |
            [
              {
                "name": "myApp2",
                "version": "1.0.02",
                "url": "docker.io/myapp/myimg:1.0.02"
              }
            ]
            
      - name: Print output parameter artifact IDs
        uses: docker://alpine:latest
        shell: sh
        run: |
          echo "Artifact IDs: ${{ steps.register.outputs.artifact-ids }}"
